import type { Topic } from "@/types";

export const topics: Topic[] = [
  // ════════════════════════════════════════════════════════════════
  // FASE 1 — PURPLE TEAM FOUNDATIONS
  // ════════════════════════════════════════════════════════════════

  // ── Bloco 1 — Base ──────────────────────────────────────────
  {
    id: 1,
    slug: "linux",
    module: "Módulo 1",
    phase: "Fase 1 — Purple Team Foundations",
    block: "Bloco 1 — Base",
    title: "Linux, do zero absoluto",
    emoji: "terminal",
    desc: "Do zero absoluto ao terminal, sistema de arquivos e shell scripting.",
    longDesc: "Linux é a base de qualquer profissional de segurança. Neste módulo aprendes a instalar, configurar e operar um sistema Linux desde zero, dominando o terminal, permissões, processos e shell scripting para automação.",
    estimatedHours: 30,
    mainVideo: {
      title: "Introdução ao Linux (Conceitos e Questões)",
      duration: "6h 45min",
      url: "https://www.youtube.com/watch?v=ZrCrlvS2-us&t=336s",
      description: "Este vídeo começa aos 5:31 — o conteúdo antes não é relevante para o roadmap.",
    },
    lessons: [
      { id: 1, title: "O que é Linux, distribuições e filosofia Unix", duration: "45 min", topics: ["O que é o kernel e o que é uma distribuição", "Principais distribuições (Ubuntu, Debian, Fedora, Arch)", "Distribuições focadas em segurança (Kali, Parrot, Tails)", "Filosofia Unix: 'tudo é arquivo', programas que fazem uma coisa bem feita", "Código aberto vs. código fechado", "Onde o Linux é usado (servidores, embarcados, Android)"], subLessons: { drivers: { title: "Drivers", def: "Programas que permitem que o sistema operacional se comunique com dispositivos de hardware (placa de vídeo, som, rede, etc.). Sem o driver correto, o hardware pode não funcionar ou funcionar de forma limitada." }, kernel: { title: "Kernel", def: "Núcleo do sistema operacional que gerencia hardware, processos, memória e dispositivos. O Linux é tecnicamente um kernel, não um SO completo." }, shell: { title: "Shell", def: "Interpretador de comandos do terminal (bash, zsh, fish). É a interface entre o usuário e o kernel." }, distro: { title: "Distro", def: "Distribuição Linux — pacote completo que inclui kernel Linux + ferramentas GNU + gestor de pacotes + ambiente gráfico (opcional). Ex: Ubuntu, Arch, Fedora, Debian." } } },
      { id: 2, title: "Instalação e primeiro contato com o terminal", duration: "55 min", practice: true, topics: ["Ambientes: VM (VirtualBox), WSL2, dual boot, cloud", "Instalação do Ubuntu (passo a passo)", "Primeiro login e atualização do sistema (sudo apt update && sudo apt upgrade)", "Anatomia do prompt: usuario@hostname:~$", "Comandos de sobrevivência: pwd, whoami, clear, exit, man", "O que é o shell (Bash/Zsh)"] },
      { id: 3, title: "Sistema de arquivos e navegação", duration: "40 min", topics: ["A raiz / e os diretórios essenciais: /etc, /var, /home, /tmp, /boot, /usr", "Caminhos absolutos vs. relativos", "Navegação: cd, ls -la, pwd", "Criar e remover diretórios: mkdir, rmdir, rm -rf", "Ocultar arquivos (. no início do nome)", "Links simbólicos (ln -s)"] },
      { id: 4, title: "Comandos básicos (manipulação de arquivos)", duration: "50 min", topics: ["Criar arquivos vazios: touch", "Copiar: cp (arquivos e diretórios com -r)", "Mover/renomear: mv", "Remover: rm (cuidado com rm -rf)", "Visualizar: cat, less, head, tail, more", "Filtrar com grep (buscar texto dentro de arquivos)", "Contar linhas: wc -l", "Ordenar: sort"] },
      { id: 5, title: "Gerenciamento de pacotes (`apt`, `dpkg`)", duration: "40 min", topics: ["O que é o APT (Advanced Package Tool)", "Repositórios: /etc/apt/sources.list", "Atualizar lista de pacotes: sudo apt update", "Atualizar pacotes: sudo apt upgrade", "Instalar: sudo apt install nome_do_pacote", "Remover: sudo apt remove e sudo apt purge", "Buscar pacotes: apt search", "Gerenciamento local com dpkg -i (instalar .deb)"] },
      { id: 6, title: "Editores de texto (`vim`, `nano`)", duration: "35 min", practice: true, topics: ["Por que aprender um editor no terminal", "Nano: interface simples, atalhos na tela (Ctrl+O salvar, Ctrl+X sair)", "Vim: modos (comando, inserção, visual)", "Vim básico: i (inserir), Esc (sair do modo), :wq (salvar e sair), :q! (sair sem salvar)", "Navegação no Vim: h j k l, gg, G", "Criar e editar arquivos de configuração com Vim"] },
      { id: 7, title: "Permissões e usuários", duration: "45 min", topics: ["O que são permissões: rwx (leitura, escrita, execução)", "Dono, grupo, outros", "Ver permissões: ls -l", "Modificar permissões com chmod (modo numérico: 755, 644; modo simbólico: u+x)", "Modificar dono e grupo: chown, chgrp", "Gerenciar usuários: useradd, passwd, usermod", "Arquivos /etc/passwd e /etc/shadow", "Sudo e o arquivo /etc/sudoers"] },
      { id: 8, title: "Processos e gerenciamento de serviços (`systemd`)", duration: "40 min", topics: ["O que é um processo (PID, PPID)", "Listar processos: ps aux, ps -ef", "Monitorar em tempo real: top, htop", "Matar processos: kill, kill -9", "O que é o systemd (inicialização e gerenciamento de serviços)", "Comandos: systemctl start/stop/restart/status", "Habilitar serviço na inicialização: systemctl enable/disable", "Ver serviços ativos: systemctl list-units --type=service --state=running", "Logs de serviços: journalctl -u nome_servico"] },
      { id: 9, title: "Shell scripting (Bash) — automação", duration: "1h 10min", practice: true, topics: ["O que é um script Bash e para que serve", "Shebang: #!/bin/bash", "Variáveis: NOME=\"valor\", $NOME", "Entrada do usuário: read", "Laços: for, while", "Condicionais: if, elif, else, test ou [ ]", "Argumentos do script: $0, $1, $#, $@", "Permissão de execução: chmod +x script.sh", "Agendamento com cron e crontab", "Projeto: Criar script que enumera usuários com shell /bin/bash"] },
      { id: 10, title: "Redes no Linux (diagnóstico e configuração)", duration: "45 min", topics: ["Comandos de diagnóstico: ping, traceroute, mtr", "Ver interfaces de rede: ip a (substituto do ifconfig)", "Ver rotas: ip route (substituto do route -n)", "Ver portas abertas e conexões: ss (substituto do netstat): ss -tulpn", "Configurar IP estático vs. DHCP", "Resolver DNS: /etc/resolv.conf e dig/nslookup", "Firewall básico: ufw (Uncomplicated Firewall)", "Reiniciar serviço de rede: systemctl restart networking ou nmcli"] },
    ],
    resources: [
      { type: "video", title: "Professor Messer — Linux+ / CompTIA A+", free: true, url: "https://www.youtube.com/watch?v=uvFqEofDwt4" },
      { type: "platform", title: "OverTheWire — Bandit (wargame de Linux)", free: true, url: "https://overthewire.org/wargames/bandit/" },
      { type: "book", title: "The Linux Command Line", author: "William Shotts", free: true, url: "https://linuxcommand.org/tlcl.php" },
      { type: "platform", title: "TryHackMe — Linux Fundamentals", free: true, url: "https://tryhackme.com/room/linuxfundamentalspart1" },
    ],
    deepDive: [
      { type: "article", title: "Linux Privilege Escalation Guide — GTFOBins", free: true, url: "https://gtfobins.github.io/" },
      { type: "book", title: "Linux Administration: A Beginner's Guide", author: "Wale Soyinka", free: false },
    ],
  },
  {
    id: 2,
    slug: "redes",
    module: "Módulo 2",
    phase: "Fase 1 — Purple Team Foundations",
    block: "Bloco 1 — Base",
    title: "Networking, do zero absoluto",
    emoji: "network",
    desc: "Modelo OSI, TCP/IP, subnetting, protocolos e análise de tráfego.",
    longDesc: "Redes são a base de tudo em segurança. Sem entender como pacotes viajam, protocolos funcionam e tráfego se comporta, não é possível identificar anomalias nem ataques. Este módulo cobre o essencial para ter uma base sólida de redes.",
    estimatedHours: 28,
    mainVideo: { title: "CompTIA Network+ Full Course", duration: "7h 20min", url: "https://youtube.com/watch?v=example_network" },
    lessons: [
      { id: 1, title: "Modelo OSI vs TCP/IP — A pilha da internet", duration: "50 min", topics: ["Camadas do modelo OSI", "Modelo TCP/IP: aplicação, transporte, rede, enlace", "Encapsulamento de dados", "Comparação OSI vs TCP/IP", "Por que isso importa para segurança"] },
      { id: 2, title: "MAC Address e ARP — Como os dispositivos se encontram", duration: "45 min", topics: ["O que é MAC Address", "Formato e unicidade", "Protocolo ARP: resolução de endereços", "Tabela ARP e cache", "ARP spoofing como vetor de ataque"] },
      { id: 3, title: "IPv4 e Sub-redes — Cálculo na mão", duration: "1h", practice: true, topics: ["Estrutura do IPv4", "Classes de endereços", "Máscaras de sub-rede e CIDR", "Cálculo manual de sub-redes", "Sub-redes privadas e públicas"] },
      { id: 4, title: "TCP vs UDP — O confiável vs. o rápido", duration: "45 min", topics: ["Three-way handshake", "Portas e sockets", "Controle de fluxo e janela", "UDP: conexão simples e rápida", "Quando usar cada um"] },
      { id: 5, title: "DNS — A agenda telefônica da internet", duration: "50 min", topics: ["Hierarquia DNS: root, TLD, autoritativo", "Registros: A, AAAA, CNAME, MX, TXT", "Resolução recursiva vs iterativa", "Ferramentas: dig, nslookup", "DNS como vetor de ataque"] },
      { id: 6, title: "DHCP — Como seu IP é entregue automaticamente", duration: "40 min", topics: ["Funcionamento DORA (Discover, Offer, Request, Ack)", "Concessão e renovação", "Escopo e reservas", "DHCP spoofing e ataques", "Configuração básica"] },
      { id: 7, title: "HTTP/HTTPS e TLS — A linguagem da web", duration: "50 min", topics: ["Estrutura de requisição/resposta", "Métodos HTTP: GET, POST, PUT, DELETE", "Cabeçalhos e cookies", "Handshake TLS", "HTTPS e certificados"] },
      { id: 8, title: "Firewalls e NAT — O porteiro e o tradutor", duration: "45 min", topics: ["Firewall: conceito e tipos (stateful, stateless)", "Regras de firewall", "NAT: tradução de endereços", "Port forwarding", "DMZ e segmentação de rede"] },
      { id: 9, title: "SSH — Configuração, chaves e túneis", duration: "1h", practice: true, topics: ["Autenticação por senha vs chave", "Geração de chaves ssh-keygen", "Configuração do servidor sshd", "Túneis SSH (local, remoto)", "Melhores práticas de segurança"] },
      { id: 10, title: "VPN, Proxy e DMZ — Conceitos finais", duration: "40 min", topics: ["VPN: site-to-site e remote access", "Proxy: forward e reverse", "DMZ: zona desmilitarizada", "Casos de uso em segurança", "Revisão do bloco de redes"] },
    ],
    resources: [
      { type: "video", title: "Professor Messer — CompTIA Network+", free: true, url: "https://www.youtube.com/watch?v=vrhnn4KjhWA" },
      { type: "tool", title: "Wireshark — captura e análise de pacotes", free: true, url: "https://www.wireshark.org/" },
      { type: "platform", title: "PicoCTF — desafios de rede", free: true, url: "https://play.picoctf.org/" },
    ],
    deepDive: [
      { type: "book", title: "TCP/IP Illustrated", author: "W. Richard Stevens", free: false },
      { type: "article", title: "RFC 791 — Internet Protocol", free: true },
    ],
  },
  {
    id: 3,
    slug: "python-seguranca",
    module: "Módulo 3",
    phase: "Fase 1 — Purple Team Foundations",
    block: "Bloco 1 — Base",
    title: "Python aplicado à segurança + Algoritmos",
    emoji: "python",
    desc: "Fundamentos de Python, automação, sockets, APIs, banco de dados e Docker.",
    longDesc: "Python é a linguagem da segurança moderna. Usada para automatizar tarefas, criar scanners de rede, forjar pacotes, interagir com APIs e construir ferramentas. Este módulo cobre desde a sintaxe básica até a containerização de uma aplicação.",
    estimatedHours: 30,
    mainVideo: { title: "Python para Hackers e Pentesters", duration: "5h 45min", url: "https://youtube.com/watch?v=example_python" },
    lessons: [
      { id: 1, title: "Revisão de sintaxe — Variáveis, tipos e estruturas de dados", duration: "50 min", topics: ["Variáveis e tipos básicos", "Listas, tuplas, dicionários, sets", "Manipulação de strings", "Entrada e saída", "Boas práticas de código"] },
      { id: 2, title: "Estruturas de controle — `if`, `for`, `while`", duration: "45 min", topics: ["Condicionais: if/elif/else", "Loops: for e while", "Compreensão de listas", "Tratamento de exceções", "Exemplos práticos"] },
      { id: 3, title: "Funções e escopo — Organizando o código", duration: "45 min", topics: ["Definição de funções", "Parâmetros e argumentos", "Escopo: global vs local", "Funções lambda", "Módulos e importação"] },
      { id: 4, title: "Manipulação de arquivos e strings — O parsing", duration: "50 min", topics: ["Leitura e escrita de arquivos", "Modos: r, w, a", "Parsing de CSV e JSON", "Expressões regulares", "Exemplo: parser de logs"] },
      { id: 5, title: "Biblioteca `socket` — Conexões TCP/UDP na unha", duration: "1h", practice: true, topics: ["Socket TCP: cliente e servidor", "Socket UDP", "Criação de um chat simples", "Banner grabbing com socket", "Tratamento de erros"] },
      { id: 6, title: "`subprocess` e `scapy` — Executando comandos e forjando pacotes", duration: "1h 10min", practice: true, topics: ["Execução de comandos com subprocess", "Scapy: forjamento de pacotes", "ARP scan com Scapy", "DNS queries com Scapy", "Automação de nmap"] },
      { id: 7, title: "`requests` e `paramiko` — Interagindo com a web e SSH", duration: "1h", topics: ["Requisições HTTP com requests", "Autenticação e sessões", "Paramiko: automação SSH", "Execução remota de comandos", "Exemplo: script de reconhecimento"] },
      { id: 8, title: "FastAPI — Construindo sua primeira API REST", duration: "1h 15min", practice: true, topics: ["FastAPI vs Flask", "Rotas e métodos HTTP", "Validação com Pydantic", "Documentação automática (Swagger)", "API de exemplo"] },
      { id: 9, title: "Banco de Dados (SQLite) e Testes (`pytest`)", duration: "1h", practice: true, topics: ["SQLite com Python (sqlite3)", "Operações CRUD", "Introdução ao pytest", "Testes unitários da API", "Cobertura de código"] },
      { id: 10, title: "Docker — Containerizando sua aplicação", duration: "1h", practice: true, topics: ["O que é Docker", "Dockerfile: criação de imagem", "Docker Compose: múltiplos serviços", "Volumes e persistência", "Docker para segurança"] },
    ],
    resources: [
      { type: "book", title: "Automate the Boring Stuff with Python", author: "Al Sweigart", free: true, url: "https://automatetheboringstuff.com/" },
      { type: "book", title: "Black Hat Python", author: "Justin Seitz", free: false },
      { type: "platform", title: "FastAPI Documentation", free: true, url: "https://fastapi.tiangolo.com/" },
    ],
    deepDive: [
      { type: "platform", title: "HackTheBox Academy — Python para Pentesters", free: false },
      { type: "book", title: "Violent Python", author: "TJ O'Connor", free: false },
    ],
  },

  // ── Bloco 1.5 — Segurança Web e Malware ────────────────────
  {
    id: 4,
    slug: "seguranca-web",
    module: "Módulo 3.5",
    phase: "Fase 1 — Purple Team Foundations",
    block: "Bloco 1.5 — Segurança Web e Malware",
    title: "Segurança Web (OWASP Top 10)",
    emoji: "globe",
    desc: "OWASP Top 10, Burp Suite, SQL Injection, XSS, CSRF e vulnerabilidades web.",
    longDesc: "A web é o vetor de ataque mais explorado. Este módulo cobre as 10 vulnerabilidades mais críticas segundo o OWASP, com prática intensiva de exploração e mitigação usando Burp Suite e ferramentas especializadas.",
    estimatedHours: 28,
    mainVideo: { title: "OWASP Top 10 — Web Security Course", duration: "6h 00min", url: "https://youtube.com/watch?v=example_owasp" },
    lessons: [
      { id: 1, title: "OWASP Top 10 — Visão Geral e Configuração do Ambiente", duration: "50 min", practice: true, topics: ["O que é OWASP Top 10", "Configuração do laboratório", "DVWA e Webgoat", "Ferramentas essenciais", "Metodologia de teste"] },
      { id: 2, title: "Burp Suite — Proxy, Repeater e Intruder", duration: "1h", practice: true, topics: ["Proxy de interceptação", "Repeater: repetição de requisições", "Intruder: ataques automatizados", "Decoder e comparador", "Extensões do Burp"] },
      { id: 3, title: "SQL Injection — O clássico que nunca morre", duration: "1h 10min", practice: true, topics: ["Detecção de SQLi", "Extraindo dados com UNION", "Information_schema", "SQLi em login bypass", "Ferramentas: sqlmap"] },
      { id: 4, title: "SQL Injection — Aprofundamento (Blind e Automatização)", duration: "1h", practice: true, topics: ["Blind SQLi: boolean-based", "Time-based SQLi", "Out-of-band SQLi", "Automatização com scripts", "Mitigação: prepared statements"] },
      { id: 5, title: "Cross-Site Scripting (XSS) — Refletido, Armazenado e DOM", duration: "1h", practice: true, topics: ["XSS refletido", "XSS armazenado", "DOM-based XSS", "Payloads comuns", "Mitigação: CSP e encoding"] },
      { id: 6, title: "Cross-Site Request Forgery (CSRF)", duration: "50 min", topics: ["O que é CSRF", "Criação de payload CSRF", "Exploração em formulários", "Tokens anti-CSRF", "SameSite cookies"] },
      { id: 7, title: "Broken Authentication e Session Management", duration: "45 min", topics: ["Falhas de autenticação", "Credential stuffing", "Session fixation", "JWT vulnerabilities", "Boas práticas de autenticação"] },
      { id: 8, title: "Security Misconfiguration e Broken Access Control (IDOR)", duration: "50 min", topics: ["Security misconfiguration", "IDOR: Insecure Direct Object Reference", "Path traversal", "Directory listing", "Headers de segurança"] },
      { id: 9, title: "Software Supply Chain Failures (Novo na lista de 2025)", duration: "45 min", topics: ["Ataques a dependências", "Malware em pacotes", "Verificação de integridade", "SBOM (Software Bill of Materials)", "Boas práticas de supply chain"] },
      { id: 10, title: "Revisão, Correção e Write-up", duration: "1h", practice: true, topics: ["Revisão de todas as vulnerabilidades", "Correção das falhas", "Estrutura de write-up", "Documentação de achados", "Relatório final do módulo"] },
    ],
    resources: [
      { type: "platform", title: "OWASP Top 10 — Site oficial", free: true, url: "https://owasp.org/www-project-top-ten/" },
      { type: "tool", title: "Burp Suite Community Edition", free: true, url: "https://portswigger.net/burp" },
      { type: "platform", title: "PortSwigger Web Security Academy", free: true, url: "https://portswigger.net/web-security" },
    ],
    deepDive: [
      { type: "book", title: "The Web Application Hacker's Handbook", author: "Stuttard & Pinto", free: false },
      { type: "platform", title: "PentesterLab — Web challenges", free: false },
    ],
  },
  {
    id: 5,
    slug: "malware-fundamentals",
    module: "Módulo 3.6",
    phase: "Fase 1 — Purple Team Foundations",
    block: "Bloco 1.5 — Segurança Web e Malware",
    title: "Malware Fundamentals",
    emoji: "skull",
    desc: "Tipos de malware, análise estática/dinâmica, YARA e MITRE ATT&CK.",
    longDesc: "Compreender malware é essencial para quem trabalha com segurança. Este módulo cobre os tipos de malware, seu ciclo de ataque, técnicas de evasão e as ferramentas fundamentais para análise estática e dinâmica.",
    estimatedHours: 25,
    mainVideo: { title: "Malware Analysis Fundamentals", duration: "5h 00min", url: "https://youtube.com/watch?v=example_malware" },
    lessons: [
      { id: 1, title: "Tipos de Malware — Vírus, Worms, Trojans, Ransomware, Rootkits", duration: "45 min", topics: ["Vírus e worms", "Trojans e backdoors", "Ransomware: como funciona", "Rootkits: ocultação no sistema", "Spyware e adware"] },
      { id: 2, title: "O Ciclo de Ataque (Cyber Kill Chain vs. MITRE ATT&CK)", duration: "50 min", topics: ["Cyber Kill Chain: 7 fases", "MITRE ATT&CK: matriz de TTPs", "Mapeamento de ataques reais", "Diferenças e complementaridade", "Aplicação prática"] },
      { id: 3, title: "Persistência — Como o malware 'gruda' no sistema", duration: "45 min", topics: ["Mecanismos de persistência no Linux", "Mecanismos de persistência no Windows", "Registro e tarefas agendadas", "Cron jobs e systemd", "Detecção de persistência"] },
      { id: 4, title: "Evasão e Ofuscação — Como o malware se esconde", duration: "50 min", topics: ["Ofuscação de código", "Packers e crypters", "Anti-debug e anti-VM", "Polimorfismo e metamorfismo", "Técnicas de evasão de AV"] },
      { id: 5, title: "Análise Estática — Olhando o código sem executar", duration: "1h", practice: true, topics: ["Strings analysis", "PE/ELF structure analysis", "Hashing de amostras", "VirusTotal e sandboxes", "Ferramentas: pestr, exiftool, die"] },
      { id: 6, title: "Análise Dinâmica — Executando com segurança (Sandbox)", duration: "1h 10min", practice: true, topics: ["Configuração de sandbox", "Monitoramento de processos", "Análise de chamadas de sistema", "Ferramentas: Process Monitor, Procmon", "Registros de atividade"] },
      { id: 7, title: "Comportamento de Rede — C2, Beaconing e DNS Tunneling", duration: "50 min", topics: ["C2: comando e controle", "Beaconing: periodicidade", "DNS tunneling", "Análise de PCAPs maliciosos", "Ferramentas: Wireshark, Zeek"] },
      { id: 8, title: "Ferramentas Avançadas — IDA Free / Ghidra (Noções básicas)", duration: "1h", practice: true, topics: ["Descompiladores vs disassemblers", "Ghidra: navegação básica", "IDA Free: funcionalidades", "Análise de funções suspeitas", "Identificação de strings ofuscadas"] },
      { id: 9, title: "YARA — A 'Receita de Bolo' para detectar malwares", duration: "50 min", practice: true, topics: ["Sintaxe YARA: regras e condições", "Criação de regras simples", "Identificação de padrões", "YARA em escala", "Exemplos práticos"] },
      { id: 10, title: "Relatório e Consolidação — Write-up de Análise", duration: "1h", practice: true, topics: ["Estrutura de relatório de análise", "Inclusão de IoCs", "Documentação de comportamento", "Recomendações de detecção", "Entrega do write-up final"] },
    ],
    resources: [
      { type: "tool", title: "Ghidra — Reverse Engineering", free: true, url: "https://ghidra-sre.org/" },
      { type: "tool", title: "YARA — Pattern matching tool", free: true, url: "https://virustotal.github.io/yara/" },
      { type: "platform", title: "VirusTotal — Análise de amostras", free: true, url: "https://www.virustotal.com/" },
    ],
    deepDive: [
      { type: "book", title: "Practical Malware Analysis", author: "Michael Sikorski", free: false },
      { type: "platform", title: "TryHackMe — Malware Analysis Path", free: true },
    ],
  },

  // ── Bloco 2 — SOC Analyst ──────────────────────────────────
  {
    id: 6,
    slug: "logging-siem",
    module: "Módulo 4",
    phase: "Fase 1 — Purple Team Foundations",
    block: "Bloco 2 — SOC Analyst",
    title: "Logging, Monitoramento e SIEM",
    emoji: "gauge",
    desc: "SIEM, Elastic Stack, Wazuh, correlação de alertas e dashboards.",
    longDesc: "Logging e monitoramento são os olhos do SOC. Neste módulo aprendes a configurar e utilizar SIEMs como Elastic Stack e Wazuh, analisar logs, criar alertas de correlação e construir dashboards de segurança.",
    estimatedHours: 22,
    mainVideo: { title: "Elastic Stack para SOC", duration: "5h 00min", url: "https://youtube.com/watch?v=example_elastic" },
    lessons: [
      { id: 1, title: "O que é um SIEM e por que logs são importantes", duration: "45 min", topics: ["O que é um SIEM", "Fontes de log: servidores, firewalls, endpoints", "Centralização de logs", "Valor do SIEM para o SOC", "Visão geral do mercado"] },
      { id: 2, title: "Arquitetura da Elastic Stack (ELK) — O SIEM gratuito", duration: "50 min", practice: true, topics: ["Elasticsearch: armazenamento e busca", "Logstash: processamento de logs", "Kibana: visualização e dashboards", "Elastic Agent e Fleet", "Instalação e configuração inicial"] },
      { id: 3, title: "Coleta de logs — Configurando o Filebeat", duration: "1h", practice: true, topics: ["O que é Filebeat", "Configuração de inputs", "Envio para Elasticsearch", "Módulos pré-configurados", "Verificação de funcionamento"] },
      { id: 4, title: "Normalização e Parsing — Transformando bagunça em dados", duration: "1h", topics: ["ES Mapping e field types", "Ingest pipelines", "Dissect e Grok patterns", "ECS (Elastic Common Schema)", "Tratamento de logs mal formatados"] },
      { id: 5, title: "Indexação e Busca — KQL e Lucene", duration: "50 min", topics: ["Criação de índices", "KQL: Kibana Query Language", "Lucene query syntax", "Filtros e intervalos de tempo", "Salvando buscas frequentes"] },
      { id: 6, title: "Dashboards — Visualizando a saúde da rede", duration: "1h", practice: true, topics: ["Criação de visualizações", "Tipos de gráficos", "Montagem de dashboard", "Drill-down e interatividade", "Exportação e compartilhamento"] },
      { id: 7, title: "Regras de Correlação e Alertas (Watchers / Rules)", duration: "1h 10min", topics: ["Conceitos de correlação", "Elastic Rules", "Criação de watchers", "Thresholds e suppressão", "Notificações e ações"] },
      { id: 8, title: "Wazuh — O SIEM Open-Source com HIDS embutido", duration: "1h", practice: true, topics: ["Instalação do Wazuh", "Agentes: deploy e configuração", "FIM (File Integrity Monitoring)", "Detecção de malware", "Integração com Elastic Stack"] },
      { id: 9, title: "Threat Hunting — Indo atrás do invasor", duration: "50 min", topics: ["O que é Threat Hunting", "Hipóteses baseadas em MITRE ATT&CK", "Busca por IoCs e TTPs", "Ferramentas de hunting", "Documentação de descobertas"] },
      { id: 10, title: "Revisão e Melhores Práticas (Arquitetura de Logs)", duration: "45 min", topics: ["Arquitetura de logging escalável", "Retenção e armazenamento", "Compliance e regulamentação", "Playbook de resposta a alertas", "Revisão final do módulo"] },
    ],
    resources: [
      { type: "tool", title: "Elastic Stack", free: true, url: "https://www.elastic.co/what-is/elk-stack" },
      { type: "tool", title: "Wazuh — SIEM Open Source", free: true, url: "https://wazuh.com/" },
      { type: "platform", title: "TryHackMe — SIEM Deep Dive", free: true },
    ],
    deepDive: [
      { type: "article", title: "Building a Home SIEM Lab", free: true },
      { type: "book", title: "Learning Splunk", author: "James Miller", free: false },
    ],
  },
  {
    id: 7,
    slug: "deteccao-hardening",
    module: "Módulo 5",
    phase: "Fase 1 — Purple Team Foundations",
    block: "Bloco 2 — SOC Analyst",
    title: "Detecção de Intrusão e Hardening",
    emoji: "shield",
    desc: "IDS/IPS, Snort/Suricata, regras de assinatura, hardening CIS.",
    longDesc: "Detecção de intrusão e hardening são pilares da defesa. Este módulo combina a configuração de IDS/IPS como Snort e Suricata com a aplicação de CIS Benchmarks para hardening de sistemas.",
    estimatedHours: 20,
    mainVideo: { title: "Network Intrusion Detection e Hardening", duration: "4h 30min", url: "https://youtube.com/watch?v=example_ids" },
    lessons: [
      { id: 1, title: "IDS vs. IPS — O que são e qual a diferença", duration: "45 min", topics: ["IDS: detecção passiva", "IPS: prevenção ativa", "Modos de operação", "Assinaturas vs anomalias", "Casos de uso"] },
      { id: 2, title: "Instalação e Configuração do Snort/Suricata", duration: "1h", practice: true, topics: ["Instalação do Snort", "Instalação do Suricata", "Configuração de interfaces", "Modos inline e passivo", "Teste de funcionamento"] },
      { id: 3, title: "Regras — A linguagem de assinatura", duration: "1h 10min", practice: true, topics: ["Sintaxe de regras Snort", "Cabeçalho e opções", "Criação de regras customizadas", "Teste com PCAPs", "Otimização de regras"] },
      { id: 4, title: "Análise de PCAPs — Caçando ameaças offline", duration: "1h", topics: ["Estrutura de um PCAP", "Ferramentas: tcpdump, Wireshark", "Extração de fluxos", "Identificação de ataques em PCAPs", "Criação de regras a partir de PCAPs"] },
      { id: 5, title: "IoCs (Indicadores de Compromisso) — Hashes, IPs e Domínios", duration: "50 min", topics: ["Tipos de IoC", "Fontes de threat intelligence", "Automação de IoCs em regras", "MISP: plataforma de sharing", "Integração com IDS"] },
      { id: 6, title: "Alertas em Tempo Real — Integrando com o SIEM", duration: "1h", topics: ["Output do Suricata para Elastic", "Syslog e alertas", "Dashboards de alertas", "Correlação IDS + SIEM", "Playbook de resposta"] },
      { id: 7, title: "Hardening — CIS Benchmarks (Linux)", duration: "50 min", practice: true, topics: ["O que são CIS Benchmarks", "Níveis 1 e 2", "Aplicação manual de benchmarks", "Lynis: auditoria automática", "OpenSCAP: compliance automatizado"] },
      { id: 8, title: "Hardening na Prática — SSH, Firewall e Serviços", duration: "1h", topics: ["Hardening de SSH (chaves, porta, auth)", "Configuração de firewall (iptables/ufw)", "Desabilitação de serviços", "Segurança de kernel (sysctl)", "Ferramentas: fail2ban"] },
      { id: 9, title: "Hardening no Windows e Ferramentas Automáticas (Lynis/OpenSCAP)", duration: "1h", topics: ["Hardening de Windows Server", "Políticas de grupo (GPO)", "Windows Defender e firewall", "Lynis para Windows", "OpenSCAP no Windows"] },
      { id: 10, title: "Revisão Final — Playbook de Defesa", duration: "50 min", topics: ["Compilação de playbook", "Procedimentos operacionais", "Checklist de hardening", "Documentação de detecção", "Revisão do módulo"] },
    ],
    resources: [
      { type: "tool", title: "Snort — IDS open source", free: true, url: "https://www.snort.org/" },
      { type: "tool", title: "Suricata — IDS/IPS de alta performance", free: true, url: "https://suricata.io/" },
      { type: "tool", title: "Lynis — Auditoria de segurança Linux", free: true },
    ],
    deepDive: [
      { type: "article", title: "CIS Benchmarks — Site oficial", free: true, url: "https://www.cisecurity.org/cis-benchmarks" },
      { type: "book", title: "Security Engineering", author: "Ross Anderson", free: true },
    ],
  },

  // ── Bloco 3 — Pentester Jr ─────────────────────────────────
  {
    id: 8,
    slug: "reconhecimento-exploracao",
    module: "Módulo 6",
    phase: "Fase 1 — Purple Team Foundations",
    block: "Bloco 3 — Pentester Jr",
    title: "Reconhecimento e Exploração",
    emoji: "search",
    desc: "OSINT, Nmap, enumeração, Metasploit, exploração web e privilege escalation.",
    longDesc: "Reconhecimento é a fase mais crítica de qualquer pentest. Este módulo cobre desde OSINT e enumeração até exploração com Metasploit, escalonamento de privilégios e comprometimento de serviços.",
    estimatedHours: 28,
    mainVideo: { title: "Pentest — Reconhecimento e Exploração", duration: "6h 00min", url: "https://youtube.com/watch?v=example_pentest" },
    lessons: [
      { id: 1, title: "Metodologia de Pentest e Configuração do Laboratório", duration: "50 min", practice: true, topics: ["Fases do pentest", "Escopo e regras de engajamento", "Configuração do lab (Kali + metasploitable)", "Ferramentas essenciais", "Documentação inicial"] },
      { id: 2, title: "OSINT — Reconhecimento Passivo", duration: "45 min", practice: true, topics: ["Google dorks", "Shodan: busca por dispositivos", "theHarvester: emails e subdomínios", "Maltego: visualização de relações", "Ética e legalidade"] },
      { id: 3, title: "Escaneamento de Rede e Descoberta de Serviços (Nmap Avançado)", duration: "1h", practice: true, topics: ["Tipos de scan: TCP, SYN, UDP", "NSE: scripts do Nmap", "Detecção de SO e versões", "Evasão de firewall", "Otimização de scans"] },
      { id: 4, title: "Enumeração Web — Diretórios, Subdomínios e Tecnologias", duration: "1h", topics: ["Enumeração de diretórios (gobuster, dirb)", "Enumeração de subdomínios", "Identificação de tecnologias (whatweb)", "Wappalyzer e fingerprinting", "Mapeamento do ataque"] },
      { id: 5, title: "Enumeração de Serviços Comuns (SMB, FTP, SNMP, LDAP)", duration: "50 min", topics: ["SMB: enumeração e shares", "FTP: anônimo e credenciais", "SNMP: community strings", "LDAP: consultas e descoberta", "Ferramentas: enum4linux, snmpwalk"] },
      { id: 6, title: "Introdução ao Metasploit Framework (Arquitetura e Módulos)", duration: "1h", practice: true, topics: ["Arquitetura do Metasploit", "Módulos: exploit, payload, auxiliary", "Navegação no msfconsole", "Busca de exploits", "Configuração de payloads"] },
      { id: 7, title: "Exploração Web — Manual e com Metasploit", duration: "1h 10min", practice: true, topics: ["Exploração de LFI/RFI", "Upload de shell", "SQLi para RCE", "Metasploit: web exploits", "Pós-exploração inicial"] },
      { id: 8, title: "Exploração de Serviços de Rede (vsftpd, UnrealIRCd, etc.)", duration: "1h", practice: true, topics: ["vsftpd: backdoor conhecido", "UnrealIRCd: exploit remoto", "Samba: vulnerabilidades", "Exploração com Metasploit", "Automação de exploração"] },
      { id: 9, title: "Escalonamento de Privilégios — Linux (manual e automatizado)", duration: "1h 10min", practice: true, topics: ["Enumeração de sistema", "SUID/SGID binaries", "Exploração de cron jobs", "Kernel exploits", "Ferramentas: LinPEAS, GTFO Bins"] },
      { id: 10, title: "Escalonamento de Privilégios — Windows (Básico)", duration: "1h", practice: true, topics: ["Enumeração do Windows", "Service permissions", "Token impersonation", "Unquoted service paths", "Ferramentas: WinPEAS, PowerUp"] },
    ],
    resources: [
      { type: "tool", title: "Nmap — network scanner", free: true, url: "https://nmap.org/" },
      { type: "tool", title: "Metasploit Framework", free: true, url: "https://www.metasploit.com/" },
      { type: "platform", title: "TryHackMe — Complete Beginner Path", free: true },
    ],
    deepDive: [
      { type: "article", title: "HackTricks — Privilege Escalation", free: true },
      { type: "book", title: "Metasploit: The Penetration Tester's Guide", author: "David Kennedy", free: false },
    ],
  },
  {
    id: 9,
    slug: "pos-exploracao-reporting",
    module: "Módulo 7",
    phase: "Fase 1 — Purple Team Foundations",
    block: "Bloco 3 — Pentester Jr",
    title: "Pós-exploração e Reporting",
    emoji: "swords",
    desc: "Persistência, lateral movement, exfiltração e relatório de pentest.",
    longDesc: "Após obter acesso inicial, o trabalho continua. Este módulo cobre persistência, movimentação lateral, coleta de credenciais, exfiltração de dados e a produção de um relatório profissional de pentest.",
    estimatedHours: 22,
    mainVideo: { title: "Post-Exploitation e Reporting Profissional", duration: "4h 30min", url: "https://youtube.com/watch?v=example_postexploit" },
    lessons: [
      { id: 1, title: "Persistência no Linux — Cron, systemd, chaves SSH", duration: "1h", practice: true, topics: ["Persistência com cron", "Serviços systemd maliciosos", "Chaves SSH autorizadas", "Backdoors em binários", "Detecção de persistência"] },
      { id: 2, title: "Persistência no Windows — Registro, serviços, tarefas agendadas", duration: "1h", practice: true, topics: ["Run e RunOnce no registro", "Serviços maliciosos", "Tarefas agendadas", "Startup folders", "WMI persistence"] },
      { id: 3, title: "Movimentação Lateral (Pivoting) — SSH Tunneling, Proxychains", duration: "1h 10min", practice: true, topics: ["Pivoting: por que é necessário", "SSH tunneling: local e remoto", "Proxychains: roteamento de tráfego", "Metasploit pivot", "Ferramentas: chisel, ligolo"] },
      { id: 4, title: "Coleta de Credenciais (Linux) — `/etc/shadow`, `mimipenguin`", duration: "50 min", topics: ["Arquivos de senhas Linux", "Dumping de /etc/shadow", "Mimipenguin: senhas na memória", "Keylogging e captura", "Proteção de credenciais"] },
      { id: 5, title: "Coleta de Credenciais (Windows) — SAM, LSASS, Mimikatz", duration: "1h", practice: true, topics: ["SAM: hash de senhas", "LSASS: senhas em memória", "Mimikatz: dump de credenciais", "Pass-the-hash", "Proteção: Credential Guard"] },
      { id: 6, title: "Exfiltração de Dados — HTTP, DNS, HTTPS, compressão", duration: "1h", topics: ["Canais de exfiltração", "Exfiltração via HTTP", "DNS tunneling para dados", "Criptografia e ofuscação", "Detecção de exfiltração"] },
      { id: 7, title: "Limpeza de Rastros (Covering Tracks) — Logs, timestomp", duration: "50 min", topics: ["Limpeza de logs Linux", "Limpeza de logs Windows", "Timestomp: modificação de timestamps", "Remoção de ferramentas", "Anti-forense básico"] },
      { id: 8, title: "Estrutura de um Relatório de Pentest — Executivo vs. Técnico", duration: "45 min", topics: ["Público-alvo do relatório", "Sumário executivo", "Seção técnica detalhada", "Screenshots e evidências", "Recomendações de remediação"] },
      { id: 9, title: "CVSS e Classificação de Riscos", duration: "50 min", topics: ["Métricas CVSS 3.1", "Cálculo de severidade", "Risco vs impacto", "Matriz de risco", "Priorização de correções"] },
      { id: 10, title: "Walkthrough Completo e Relatório Final", duration: "1h 30min", practice: true, topics: ["Consolidação do pentest", "Redação do relatório completo", "Revisão de achados", "Formato de entrega", "Apresentação ao cliente"] },
    ],
    resources: [
      { type: "article", title: "HackTricks — Post-Exploitation", free: true },
      { type: "tool", title: "Mimikatz", free: true, url: "https://github.com/gentilkiwi/mimikatz" },
      { type: "article", title: "Template de relatório de pentest", free: true },
    ],
    deepDive: [
      { type: "book", title: "The Hacker Playbook 3", author: "Peter Kim", free: false },
      { type: "platform", title: "Hack The Box — Pro Labs", free: false },
    ],
  },

  // ── Bloco 4 — Purple Team ──────────────────────────────────
  {
    id: 10,
    slug: "purple-team-integration",
    module: "Módulo 8",
    phase: "Fase 1 — Purple Team Foundations",
    block: "Bloco 4 — Purple Team",
    title: "Purple Team Integration",
    emoji: "layers",
    desc: "Integração ataque+defesa, simulação simultânea e melhoria contínua.",
    longDesc: "Purple Team é a convergência entre ataque e defesa. Este módulo integra tudo o que foi aprendido: simular ataques enquanto o monitoramento está ativo, melhorar regras de detecção com base em exploração real e documentar o ciclo completo.",
    estimatedHours: 20,
    mainVideo: { title: "Purple Team — A integração ataque e defesa", duration: "4h 00min", url: "https://youtube.com/watch?v=example_purple" },
    lessons: [
      { id: 1, title: "Conceitos de Purple Team — Por que ataque e defesa juntos", duration: "35min", topics: ["Red team vs blue team", "Purple team: colaboração", "Modelo de maturidade", "Ciclo de melhoria contínua", "Ferramentas de purple team"] },
      { id: 2, title: "Simulação de Ataque com Monitoramento Ativo", duration: "1h", practice: true, topics: ["Planejamento da simulação", "Execução de ataque controlado", "Monitoramento em tempo real", "Correlação de alertas", "Documentação de descobertas"] },
      { id: 3, title: "Melhoria de Regras de Detecção baseada em Exploração", duration: "55min", practice: true, topics: ["Análise de gaps de detecção", "Criação de novas regras Snort/Suricata", "Ajuste de regras SIEM", "Teste de eficácia", "Iteração de melhoria"] },
      { id: 4, title: "Automação de Defesa com Playbooks", duration: "50min", practice: true, topics: ["O que é SOAR", "Playbooks de resposta", "Automação de blocking", "Integração de ferramentas", "Exemplo: resposta a scanning"] },
      { id: 5, title: "Teste de Penetração Completo com Documentação Defensiva", duration: "1h", practice: true, topics: ["Pentest com foco em detecção", "Mapeamento MITRE ATT&CK", "Relatório para ambos os times", "Recomendações integradas", "Métrica de melhoria"] },
      { id: 6, title: "Infraestrutura Segura — Cloud e On-Premise", duration: "45min", topics: ["Cloud security fundamentals", "Hardening de cloud (AWS/GCP)", "Segurança on-premise", "Segurança de rede corporativa", "Compliance e auditoria"] },
      { id: 7, title: "CI/CD Security — Pipeline Seguro", duration: "50min", practice: true, topics: ["SAST: análise estática", "DAST: análise dinâmica", "SCA: dependências", "Security scanning em CI/CD", "Ferramentas: SonarQube, Trivy"] },
      { id: 8, title: "Projeto Integrador — Purple Team Lab", duration: "1h 10min", practice: true, topics: ["Planejamento do lab", "Configuração de ataque e defesa", "Cenários de teste", "Relatório consolidado", "Apresentação dos resultados"] },
      { id: 9, title: "Documentação e Métricas de Sucesso", duration: "40min", topics: ["Métricas de detecção", "Tempo de resposta (MTTD, MTTR)", "Taxa de falsos positivos", "Evolução de regras", "Relatório executivo"] },
      { id: 10, title: "Revisão Final da Fase 1", duration: "45min", topics: ["Consolidação dos 8 módulos", "Avaliação de progresso", "Próximos passos", "Certificações e projetos", "Preparação para Fase 2"] },
    ],
    resources: [
      { type: "article", title: "MITRE ATT&CK Framework", free: true, url: "https://attack.mitre.org/" },
      { type: "tool", title: "Atomic Red Team — Testes de detecção", free: true },
      { type: "platform", title: "TryHackME — SOC Level 1 Path", free: true },
    ],
    deepDive: [
      { type: "book", title: "Security Automation with Ansible", author: "Mohamed Alibi", free: false },
      { type: "platform", title: "LetsDefend — SOC Analyst Training", free: false },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // FASE 2 — AI/ML ENGINEERING
  // ════════════════════════════════════════════════════════════════
  {
    id: 11,
    slug: "matematica-ml",
    module: "Módulo 9",
    phase: "Fase 2 — AI/ML Engineering",
    block: "",
    title: "Matemática para ML + Python para Dados",
    emoji: "sigma",
    desc: "Álgebra linear, estatística, Pandas, NumPy e visualização de dados.",
    longDesc: "A matemática é a linguagem do machine learning. Este módulo combina os fundamentos essenciais — álgebra linear, estatística — com as bibliotecas Python de análise de dados: NumPy, Pandas e visualização.",
    estimatedHours: 25,
    mainVideo: { title: "Mathematics for Machine Learning + Python Data", duration: "6h 00min", url: "https://youtube.com/watch?v=example_math_ml" },
    lessons: [
      { id: 1, title: "Álgebra linear — Vetores, matrizes e transformações", duration: "1h 10min", topics: ["Operações com vetores", "Matrizes e determinantes", "Transformações lineares", "Autovalores e autovetores", "Aplicações em ML"] },
      { id: 2, title: "Estatística aplicada — Média, variância, distribuições", duration: "55min", topics: ["Medidas de tendência central", "Medidas de dispersão", "Distribuições de probabilidade", "Testes estatísticos", "Aplicações em dados"] },
      { id: 3, title: "Cálculo diferencial — Derivadas e gradiente", duration: "50min", topics: ["Derivadas parciais", "Regra da cadeia", "Gradiente e direção", "Otimização com gradiente", "Aplicações em ML"] },
      { id: 4, title: "Probabilidade — Teorema de Bayes e inferência", duration: "50min", topics: ["Probabilidade básica", "Teorema de Bayes", "Inferência estatística", "Distribuições condicionais", "Aplicações em IA"] },
      { id: 5, title: "NumPy — Arrays, operações e broadcasting", duration: "50min", practice: true, topics: ["Criação de arrays", "Operações matriciais", "Broadcasting", "Indexação e fatiamento", "Performance com NumPy"] },
      { id: 6, title: "Pandas — DataFrames, filtros e agrupamentos", duration: "1h", practice: true, topics: ["Criação de DataFrames", "Filtros e seleções", "Group by e agregações", "Merge e join", "Tratamento de dados faltantes"] },
      { id: 7, title: "Matplotlib e Seaborn — Visualização de dados", duration: "55min", practice: true, topics: ["Gráficos com Matplotlib", "Visualizações estatísticas", "Seaborn para análise", "Personalização de gráficos", "Salvando e exportando"] },
      { id: 8, title: "Feature Engineering — Transformação e encoding", duration: "50min", topics: ["Normalização e padronização", "Encoding categórico", "Engenharia de features", "Seleção de features", "Pipeline de features"] },
      { id: 9, title: "Geometria de dados — Distâncias e similaridade", duration: "45min", topics: ["Métricas de distância", "Similaridade entre dados", "Espaços vetoriais", "Kernel tricks", "Visualização de dados"] },
      { id: 10, title: "Projeto Integrador — Análise de dados de segurança", duration: "1h", practice: true, topics: ["Dataset de segurança", "Análise exploratória", "Visualização de padrões", "Identificação de anomalias", "Relatório de análise"] },
    ],
    resources: [
      { type: "video", title: "3Blue1Brown — Essence of Linear Algebra", free: true },
      { type: "book", title: "Mathematics for Machine Learning", author: "Deisenroth et al.", free: true },
      { type: "platform", title: "Kaggle — Learn (Pandas, Data Visualization)", free: true },
    ],
    deepDive: [
      { type: "book", title: "Pattern Recognition and Machine Learning", author: "Christopher Bishop", free: false },
      { type: "platform", title: "MIT OCW — Linear Algebra (Gilbert Strang)", free: true },
    ],
  },
  {
    id: 12,
    slug: "ml-classico",
    module: "Módulo 10",
    phase: "Fase 2 — AI/ML Engineering",
    block: "",
    title: "Machine Learning Clássico (Scikit-learn)",
    emoji: "brain",
    desc: "Regressão, classificação, árvores, random forest, detecção de anomalias.",
    longDesc: "ML supervisionado e não-supervisionado na prática com Scikit-learn: regressão, classificação, árvores de decisão, random forests, clustering e detecção de anomalias aplicados à segurança.",
    estimatedHours: 22,
    mainVideo: { title: "Machine Learning — Scikit-learn Course", duration: "5h 30min", url: "https://youtube.com/watch?v=example_ml" },
    lessons: [
      { id: 1, title: "Regressão linear e polinomial — Previsão de valores", duration: "55min", topics: ["Regressão linear simples", "Regressão múltipla", "Regressão polinomial", "Avaliação de modelos", "Overfitting e underfitting"] },
      { id: 2, title: "Classificação — Logistic Regression e SVM", duration: "1h", topics: ["Logistic Regression", "Support Vector Machines", "Hiperplanos e margens", "Kernels em SVM", "Avaliação de classificação"] },
      { id: 3, title: "Árvores de decisão e Random Forests", duration: "55min", practice: true, topics: ["Construção de árvores", "Critérios de divisão", "Random Forests", "Ensemble methods", "Importância de features"] },
      { id: 4, title: "Avaliação de modelos — Accuracy, F1, ROC-AUC, cross-validation", duration: "50min", topics: ["Matriz de confusão", "Accuracy e F1-score", "ROC e AUC", "Cross-validation", "Curvas de aprendizado"] },
      { id: 5, title: "Regularização — L1, L2, dropout e early stopping", duration: "45min", topics: ["Regularização L1 (Lasso)", "Regularização L2 (Ridge)", "Dropout", "Early stopping", "Seleção de hiperparâmetros"] },
      { id: 6, title: "Clustering — K-Means e DBSCAN", duration: "50min", practice: true, topics: ["Algoritmo K-Means", "DBSCAN density-based", "Escolha de K", "Avaliação de clusters", "Aplicações em segurança"] },
      { id: 7, title: "Redução de dimensionalidade — PCA e t-SNE", duration: "45min", topics: ["Análise de Componentes Principais", "t-SNE para visualização", "Seleção de componentes", "Perda de variância", "Aplicações práticas"] },
      { id: 8, title: "Detecção de anomalias com Isolation Forest", duration: "45min", topics: ["Conceitos de anomaly detection", "Isolation Forest algorithm", "Treino e predição", "Thresholds e scores", "Aplicações em segurança"] },
      { id: 9, title: "Pipeline completo de ML em segurança", duration: "55min", practice: true, topics: ["Coleta e preparação de dados", "Treino e validação", "Avaliação de performance", "Interpretação de resultados", "Deploy do modelo"] },
      { id: 10, title: "Projeto — Detecção de anomalias em logs de rede", duration: "1h", practice: true, topics: ["Pré-processamento de logs", "Extração de features", "Modelo de detecção", "Avaliação e tuning", "Implementação prática"] },
    ],
    resources: [
      { type: "tool", title: "Scikit-Learn — ML em Python", free: true, url: "https://scikit-learn.org/" },
      { type: "platform", title: "Kaggle — Intro to Machine Learning", free: true },
      { type: "book", title: "Hands-On Machine Learning", author: "Aurélien Géron", free: false },
    ],
    deepDive: [
      { type: "book", title: "An Introduction to Statistical Learning", author: "James et al.", free: true },
      { type: "platform", title: "fast.ai — Practical Deep Learning", free: true },
    ],
  },
  {
    id: 13,
    slug: "deep-learning-llm",
    module: "Módulo 11",
    phase: "Fase 2 — AI/ML Engineering",
    block: "",
    title: "Deep Learning + Transformers + RAG",
    emoji: "cpu",
    desc: "PyTorch, CNNs, RNNs, Transformers, LLMs e RAG com LangChain.",
    longDesc: "Deep Learning é o motor da IA moderna. Este módulo cobre redes neurais, CNNs, RNNs, a arquitetura Transformer, LLMs (Llama, Mistral) e sistemas RAG com LangChain para aplicações práticas.",
    estimatedHours: 28,
    mainVideo: { title: "Deep Learning — Neural Networks to RAG", duration: "7h 00min", url: "https://youtube.com/watch?v=example_deep" },
    lessons: [
      { id: 1, title: "Redes neurais — Perceptron, backpropagation, activation", duration: "1h", topics: ["Perceptron e MLP", "Funções de ativação", "Backpropagation", "Otimizadores", "Treino de redes"] },
      { id: 2, title: "CNNs — Convolução, pooling e arquiteturas", duration: "55min", topics: ["Camadas convolucionais", "Pooling e stride", "Arquiteturas clássicas (ResNet, VGG)", "Transfer learning", "Aplicações em visão"] },
      { id: 3, title: "RNNs e LSTM — Modelagem de sequências", duration: "50min", topics: ["Recurrent Neural Networks", "LSTM e GRU", "Vanishing gradient", "Aplicações em séries", "Processamento de texto"] },
      { id: 4, title: "Transformers e attention mechanisms", duration: "1h 10min", topics: ["Mecanismo de attention", "Self-attention", "Arquitetura Transformer", "BERT e GPT", "Aplicações em NLP"] },
      { id: 5, title: "PyTorch na prática — Treinar um modelo do zero", duration: "1h", practice: true, topics: ["Tensores e operações", "Autograd e gradiente", "Construção de modelo", "Loop de treino", "Avaliação e teste"] },
      { id: 6, title: "LLMs — Llama, Mistral e modelos open-source", duration: "55min", topics: ["O que são LLMs", "Arquitetura dos modelos modernos", "Modelos open-source vs proprietários", "Hugging Face: carregamento de modelos", "Fine-tuning básico"] },
      { id: 7, title: "FAISS e embeddings — Busca vetorial", duration: "50min", practice: true, topics: ["O que são embeddings", "FAISS: busca de similaridade", "Índices e otimização", "Armazenamento de vetores", "Aplicações em busca"] },
      { id: 8, title: "RAG (Retrieval-Augmented Generation) com LangChain", duration: "1h 10min", practice: true, topics: ["Arquitetura RAG", "LangChain: chains e agents", "Integração com LLMs", "Bases de conhecimento", "Chain de QA"] },
      { id: 9, title: "Deploy de modelos com Hugging Face e APIs", duration: "45min", practice: true, topics: ["Hugging Face: hosting", "API de inferência", "Otimização de latência", "Quantização", "Monitoramento de modelos"] },
      { id: 10, title: "Projeto — Assistente de Segurança com RAG", duration: "1h", practice: true, topics: ["Dataset de documentos de segurança", "Pipeline RAG completo", "Interface de perguntas", "Avaliação de respostas", "Deploy do assistente"] },
    ],
    resources: [
      { type: "platform", title: "Hugging Face — Modelos e datasets", free: true, url: "https://huggingface.co/" },
      { type: "tool", title: "LangChain — Framework RAG", free: true },
      { type: "book", title: "Deep Learning", author: "Goodfellow, Bengio, Courville", free: true },
    ],
    deepDive: [
      { type: "article", title: "Attention Is All You Need — Paper original", free: true },
      { type: "platform", title: "Stanford CS231n — CNNs for Visual Recognition", free: true },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // FASE 3 — AI SECURITY EXPERT
  // ════════════════════════════════════════════════════════════════

  // ── Bloco 1 — Ameaças e Ferramentas ──────────────────────
  {
    id: 14,
    slug: "owasp-llm",
    module: "Módulo 12",
    phase: "Fase 3 — AI Security Expert",
    block: "Bloco 1 — Ameaças e Ferramentas",
    title: "OWASP Top 10 para LLMs",
    emoji: "bot",
    desc: "Prompt injection, data poisoning, model extraction e vulnerabilidades de LLMs.",
    longDesc: "LLMs estão a ser integrados em tudo — e são extremamente vulneráveis. Este módulo cobre as 10 principais ameaças a aplicações LLM segundo o OWASP, com técnicas de ataque e defesa.",
    estimatedHours: 22,
    mainVideo: { title: "LLM Security — OWASP Top 10", duration: "5h 00min", url: "https://youtube.com/watch?v=example_llm" },
    lessons: [
      { id: 1, title: "Prompt Injection — Tipos e técnicas", duration: "50min", practice: true, topics: ["Conceitos de prompt injection", "Direct vs indirect injection", "Técnicas avançadas", "Impacto em aplicações", "Defesas básicas"] },
      { id: 2, title: "Data Poisoning — Envenenamento de treino", duration: "50min", topics: ["Tipos de poisoning", "Ataques de backdoor", "Detecção de poisoning", "Defesas e mitigação", "Cenários de ataque"] },
      { id: 3, title: "Model Extraction — Clonar um modelo de terceiros", duration: "45min", topics: ["Técnicas de extração", "Query-based extraction", "Defesas contra extração", "Watermarking", "Propriedade intelectual"] },
      { id: 4, title: "Model Inversion — Extrair dados sensíveis", duration: "45min", topics: ["Membership inference", "Attribute inference", "Defesas contra inversão", "Differential privacy", "Regulamentação"] },
      { id: 5, title: "Denial of Service (DoS) em LLMs", duration: "35min", topics: ["Ataques de recurso", "Context window overflow", "Input flooding", "Rate limiting", "Mitigações"] },
      { id: 6, title: "Injeção de Contexto e Jailbreaks", duration: "50min", practice: true, topics: ["Tipos de jailbreak", "Role playing attacks", "Encoding tricks", "Multi-turn attacks", "Detecção"] },
      { id: 7, title: "Viés e Alucinações como Risco de Segurança", duration: "40min", topics: ["Viés em LLMs", "Alucinações: causas e riscos", "Impacto em segurança", "Mitigação de viés", "Auditoria de outputs"] },
      { id: 8, title: "Guardrails — Defesas e input validation", duration: "50min", practice: true, topics: ["Conceitos de guardrails", "Input validation", "Output filtering", "Content moderation", "Implementação prática"] },
      { id: 9, title: "Red Teaming de LLMs — Metodologia e ferramentas", duration: "1h", practice: true, topics: ["Metodologia de red teaming", "Ferramentas automatizadas", "Cenários de teste", "Relatório de vulnerabilidades", "Melhoria contínua"] },
      { id: 10, title: "Projeto — Auditoria de segurança de um LLM", duration: "1h", practice: true, topics: ["Escolha do alvo", "Testes de prompt injection", "Avaliação de guardrails", "Relatório de achados", "Recomendações"] },
    ],
    resources: [
      { type: "article", title: "OWASP Top 10 for LLM Applications", free: true, url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" },
      { type: "article", title: "NIST AI 100-2 — Adversarial ML Taxonomy", free: true },
      { type: "tool", title: "Garak — LLM vulnerability scanner", free: true },
    ],
    deepDive: [
      { type: "book", title: "Adversarial Machine Learning", author: "Anthony D. Joseph et al.", free: false },
      { type: "platform", title: "SecML — Course on AI Security", free: false },
    ],
  },
  {
    id: 15,
    slug: "ferramentas-ataque-defesa-ia",
    module: "Módulo 13",
    phase: "Fase 3 — AI Security Expert",
    block: "Bloco 1 — Ameaças e Ferramentas",
    title: "Ferramentas de Ataque e Defesa para IA",
    emoji: "zap",
    desc: "Garak, Giskard, PyRIT, MITRE ATLAS e frameworks de AI security.",
    longDesc: "O ecossistema de ferramentas para segurança de IA está a crescer rapidamente. Este módulo explora as principais ferramentas de ataque e defesa: Garak, Giskard, PyRIT (Microsoft) e a matriz MITRE ATLAS.",
    estimatedHours: 18,
    mainVideo: { title: "AI Security Tools — Garak, PyRIT e mais", duration: "4h 00min", url: "https://youtube.com/watch?v=example_ai_tools" },
    lessons: [
      { id: 1, title: "Garak — Scanner de vulnerabilidades para LLMs", duration: "55min", practice: true, topics: ["Instalação do Garak", "Módulos de teste", "Configuração de probes", "Execução de scans", "Interpretação de resultados"] },
      { id: 2, title: "PyRIT (Microsoft) — Framework de red teaming para IA", duration: "55min", practice: true, topics: ["Arquitetura do PyRIT", "Targets e orquestração", "Conversation history", "Avaliação de respostas", "Automação de testes"] },
      { id: 3, title: "Giskard — Testes de robustez para LLMs", duration: "50min", practice: true, topics: ["Instalação e setup", "Testes de performance", "Detecção de vulnerabilidades", "Integração contínua", "Scan de datasets"] },
      { id: 4, title: "MITRE ATLAS — Matriz de táticas e técnicas para IA", duration: "45min", topics: ["O que é MITRE ATLAS", "Mapeamento de ataques", "Diferenças para ATT&CK", "Navegação na matriz", "Aplicação prática"] },
      { id: 5, title: "Ferramentas de Defesa — Guardrails e Monitoring", duration: "50min", practice: true, topics: ["NVIDIA NeMo Guardrails", "Azure AI Content Safety", "Llama Guard", "Monitoramento de inputs/outputs", "Alertas e logging"] },
      { id: 6, title: "Integração de Ferramentas em Pipeline de Segurança", duration: "50min", practice: true, topics: ["Pipeline de AI security", "CI/CD com scans de LLM", "Dashboards agregados", "Correlação de alertas", "Melhoria contínua"] },
      { id: 7, title: "Benchmarking de Modelos — Resistência a ataques", duration: "45min", topics: ["Métricas de robustez", "Datasets de benchmark", "Comparação de modelos", "Evolução temporal", "Relatórios de segurança"] },
      { id: 8, title: "Estudos de Caso — Ataques reais a sistemas de IA", duration: "50min", topics: ["Caso 1: Prompt injection em assistente", "Caso 2: Data poisoning em chatbot", "Caso 3: Model extraction de API", "Lições aprendidas", "Recomendações"] },
      { id: 9, title: "Construção de Toolkit Próprio de AI Security", duration: "1h", practice: true, topics: ["Scripts de teste automatizados", "Integração de múltiplas ferramentas", "Dashboard unificado", "Documentação", "Compartilhamento"] },
      { id: 10, title: "Projeto — AI Security Assessment Completo", duration: "1h", practice: true, topics: ["Escopo do assessment", "Execução de ferramentas", "Relatório de vulnerabilidades", "Recomendações de mitigação", "Apresentação final"] },
    ],
    resources: [
      { type: "tool", title: "Garak — LLM vulnerability scanner", free: true, url: "https://github.com/NVIDIA/garak" },
      { type: "tool", title: "PyRIT — Microsoft AI Red Team", free: true, url: "https://github.com/Azure/PyRIT" },
      { type: "platform", title: "MITRE ATLAS", free: true, url: "https://atlas.mitre.org/" },
    ],
    deepDive: [
      { type: "tool", title: "NVIDIA NeMo Guardrails", free: true },
      { type: "article", title: "OWASP AI Security and Privacy Guide", free: true },
    ],
  },

  // ── Bloco 2 — MLSecOps e Produção ──────────────────────
  {
    id: 16,
    slug: "pipeline-ia",
    module: "Módulo 14",
    phase: "Fase 3 — AI Security Expert",
    block: "Bloco 2 — MLSecOps e Produção",
    title: "Protegendo o Pipeline de IA",
    emoji: "lock",
    desc: "Kubernetes, Vault, CI/CD seguro, monitoramento de modelos e privacidade diferencial.",
    longDesc: "MLSecOps é a prática de integrar segurança em todo o ciclo de vida de ML. Este módulo cobre infraestrutura segura (Kubernetes, Vault), CI/CD para ML, monitoramento de modelos em produção e privacidade diferencial.",
    estimatedHours: 20,
    mainVideo: { title: "MLSecOps — Secure ML Pipeline", duration: "4h 30min", url: "https://youtube.com/watch?v=example_mlsecops" },
    lessons: [
      { id: 1, title: "Kubernetes para ML — Orquestração segura", duration: "55min", practice: true, topics: ["Conceitos do Kubernetes", "Pods, serviços, deployments", "Security contexts e PSP", "Network policies", "RBAC no Kubernetes"] },
      { id: 2, title: "Vault — Gestão de segredos para ML", duration: "50min", practice: true, topics: ["O que é HashiCorp Vault", "Armazenamento de segredos", "Políticas de acesso", "Integração com aplicações ML", "Rotação de credenciais"] },
      { id: 3, title: "Pipeline CI/CD Seguro para ML", duration: "55min", practice: true, topics: ["SAST/DAST em pipeline ML", "SCA para dependências Python", "Validação de modelos", "Testes de segurança automatizados", "Ferramentas: GitLab CI, GitHub Actions"] },
      { id: 4, title: "Monitoramento de Modelos em Produção", duration: "50min", topics: ["Drift detection", "Data drift vs concept drift", "Monitoramento de performance", "Alertas de degradação", "Ferramentas: MLflow, Prometheus"] },
      { id: 5, title: "Privacidade Diferencial — Proteção de dados de treino", duration: "50min", practice: true, topics: ["Conceitos de privacidade diferencial", "Adição de ruído", "Mecanismos (Laplace, Gaussian)", "Aplicação em treino", "Trade-offs utilidade vs privacidade"] },
      { id: 6, title: "Criptografia para ML — Homomorphic encryption", duration: "45min", topics: ["Conceitos de criptografia homomórfica", "Inferência criptografada", "Limitações práticas", "Casos de uso", "Ferramentas: PySyft, TenSEAL"] },
      { id: 7, title: "Governança e Compliance para IA", duration: "40min", topics: ["Regulamentação de IA (EU AI Act)", "Documentação de modelos", "Auditoria de pipelines", "Transparência e explicabilidade", "Responsabilidade"] },
      { id: 8, title: "Incident Response para Sistemas de IA", duration: "45min", topics: ["Especificidades de incidentes em IA", "Detecção de ataques a modelos", "Contenção e erradicação", "Recuperação de modelos", "Post-mortem e lições"] },
      { id: 9, title: "Projeto Integrador — MLSecOps Pipeline", duration: "1h 10min", practice: true, topics: ["Setup de cluster Kubernetes", "Deploy de modelo com Vault", "Monitoramento com Prometheus", "Pipeline CI/CD seguro", "Documentação do projeto"] },
      { id: 10, title: "Revisão Final e Próximos Passos", duration: "45min", topics: ["Consolidação do roadmap completo", "Certificações recomendadas", "Caminhos de especialização", "Mantendo-se atualizado", "Contribuição para a comunidade"] },
    ],
    resources: [
      { type: "tool", title: "Kubernetes — Documentação oficial", free: true, url: "https://kubernetes.io/docs/" },
      { type: "tool", title: "HashiCorp Vault", free: true, url: "https://www.vaultproject.io/" },
      { type: "tool", title: "MLflow — MLOps platform", free: true },
    ],
    deepDive: [
      { type: "book", title: "Designing ML Systems", author: "Chip Huyen", free: false },
      { type: "article", title: "EU AI Act — Overview", free: true },
    ],
  },
];
